# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwid.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 802)
        MainWindow.setMinimumSize(QtCore.QSize(1002, 802))
        MainWindow.setMaximumSize(QtCore.QSize(1002, 802))
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        #MainWindow.setWindowOpacity(0.9)  # 设置窗口透明度
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_W = QtWidgets.QPushButton(self.centralwidget)
        self.Button_W.setGeometry(QtCore.QRect(200, 610, 70, 70))
        self.Button_W.setMinimumSize(QtCore.QSize(70, 70))
        self.Button_W.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_W.setFont(font)
        self.Button_W.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,60);\n"
"    border: 5px groove rgba(111, 255, 212, 30);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,50);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,60); \n"
"    border-style: inset;\n"
"}")
        self.Button_W.setObjectName("Button_W")
        self.Button_A = QtWidgets.QPushButton(self.centralwidget)
        self.Button_A.setGeometry(QtCore.QRect(130, 680, 70, 70))
        self.Button_A.setMinimumSize(QtCore.QSize(70, 70))
        self.Button_A.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_A.setFont(font)
        self.Button_A.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,60);\n"
"    border: 5px groove rgba(111, 255, 212, 30);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,50);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,60); \n"
"    border-style: inset;\n"
"}")
        self.Button_A.setObjectName("Button_A")
        self.Button_S = QtWidgets.QPushButton(self.centralwidget)
        self.Button_S.setGeometry(QtCore.QRect(200, 680, 70, 70))
        self.Button_S.setMinimumSize(QtCore.QSize(70, 70))
        self.Button_S.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_S.setFont(font)
        self.Button_S.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,60);\n"
"    border: 5px groove rgba(111, 255, 212, 30);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,50);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,60); \n"
"    border-style: inset;\n"
"}")
        self.Button_S.setObjectName("Button_S")
        self.Button_D = QtWidgets.QPushButton(self.centralwidget)
        self.Button_D.setGeometry(QtCore.QRect(270, 680, 70, 70))
        self.Button_D.setMinimumSize(QtCore.QSize(70, 70))
        self.Button_D.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_D.setFont(font)
        self.Button_D.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,60);\n"
"    border: 5px groove rgba(111, 255, 212, 30);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,50);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,60); \n"
"    border-style: inset;\n"
"}")
        self.Button_D.setObjectName("Button_D")
        self.Button_I = QtWidgets.QPushButton(self.centralwidget)
        self.Button_I.setGeometry(QtCore.QRect(470, 680, 70, 70))
        self.Button_I.setMinimumSize(QtCore.QSize(70, 70))
        self.Button_I.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_I.setFont(font)
        self.Button_I.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,60);\n"
"    border: 5px groove rgba(111, 255, 212, 30);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,50);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,60); \n"
"    border-style: inset;\n"
"}")
        self.Button_I.setObjectName("Button_I")
        self.Button_P = QtWidgets.QPushButton(self.centralwidget)
        self.Button_P.setGeometry(QtCore.QRect(470, 610, 70, 70))
        self.Button_P.setMinimumSize(QtCore.QSize(70, 70))
        self.Button_P.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_P.setFont(font)
        self.Button_P.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,60);\n"
"    border: 5px groove rgba(111, 255, 212, 30);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,50);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,60); \n"
"    border-style: inset;\n"
"}")
        self.Button_P.setObjectName("Button_P")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(690, 328, 241, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.Lab_cmd = QtWidgets.QLabel(self.centralwidget)
        self.Lab_cmd.setGeometry(QtCore.QRect(710, 388, 241, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Lab_cmd.setFont(font)
        self.Lab_cmd.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.Lab_cmd.setText("")
        self.Lab_cmd.setTextFormat(QtCore.Qt.AutoText)
        self.Lab_cmd.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_cmd.setObjectName("Lab_cmd")
        self.Lab_camera = QtWidgets.QLabel(self.centralwidget)
        self.Lab_camera.setGeometry(QtCore.QRect(70, 50, 501, 501))
        self.Lab_camera.setStyleSheet("border-radius:20px;")
        self.Lab_camera.setText("")
        self.Lab_camera.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Lab_camera.setObjectName("Lab_camera")
        self.Button_voice = QtWidgets.QPushButton(self.centralwidget)
        self.Button_voice.setGeometry(QtCore.QRect(750, 638, 161, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_voice.setFont(font)
        self.Button_voice.setStyleSheet("QPushButton{\n"
"    background:rgba(87,96,105,80);\n"
"    border: 5px groove rgba(111, 255, 212, 50);\n"
"    border-radius:20px;\n"
"    color: rgb(255,255, 255);\n"
"    selection-background-color: rgba(255,255,255,80);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgba(140, 154, 168,80); \n"
"    border-style: inset;\n"
"}")
        self.Button_voice.setObjectName("Button_voice")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(670, 448, 241, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(670, 508, 321, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(66, 204, 165);\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setOpenExternalLinks(True)
        self.label_9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(700, 38, 251, 721))
        self.lineEdit.setStyleSheet("background-color:rgba(255,255,255,60);\n"
"border-radius:20px;")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.raise_()
        self.Lab_camera.raise_()
        self.Button_W.raise_()
        self.Button_A.raise_()
        self.Button_S.raise_()
        self.Button_D.raise_()
        self.Button_I.raise_()
        self.Button_P.raise_()
        self.label_7.raise_()
        self.Lab_cmd.raise_()
        self.Button_voice.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BalanceCar Console"))
        self.Button_W.setText(_translate("MainWindow", "W"))
        self.Button_A.setText(_translate("MainWindow", "A"))
        self.Button_S.setText(_translate("MainWindow", "S"))
        self.Button_D.setText(_translate("MainWindow", "D"))
        self.Button_I.setText(_translate("MainWindow", "I"))
        self.Button_P.setText(_translate("MainWindow", "P"))
        self.label_7.setText(_translate("MainWindow", "Last Command:"))
        self.Button_voice.setText(_translate("MainWindow", "Voice Control"))
        self.label_8.setText(_translate("MainWindow", "Information:"))
